namespace AoiMeasureTool
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.MenuStrip menuStripMain;
        private System.Windows.Forms.ToolStripMenuItem menuFile;
        private System.Windows.Forms.ToolStripMenuItem menuOpenImage;
        private System.Windows.Forms.ToolStripSeparator menuFileSeparator;
        private System.Windows.Forms.ToolStripMenuItem menuExit;
        private System.Windows.Forms.ToolStripMenuItem menuEdit;
        private System.Windows.Forms.ToolStripMenuItem menuView;
        private System.Windows.Forms.ToolStripMenuItem menuHelp;
        private System.Windows.Forms.Panel panelSidebar;
        private System.Windows.Forms.Label labelAppName;
        private System.Windows.Forms.Label labelNavigation;
        private System.Windows.Forms.Button buttonLoadImage;
        private System.Windows.Forms.Label labelOpenCvStatus;
        private System.Windows.Forms.Panel panelMain;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Label labelTitle;
        private System.Windows.Forms.Label labelImageInfo;
        private System.Windows.Forms.TabControl tabControlMain;
        private System.Windows.Forms.TabPage tabPageImageViewer;
        private System.Windows.Forms.TabPage tabPageBinarization;
        private System.Windows.Forms.Label labelWorkspace;
        private System.Windows.Forms.Panel panelImageViewport;
        private System.Windows.Forms.PictureBox pictureBoxImage;
        private System.Windows.Forms.Panel panelPreprocess1;
        private System.Windows.Forms.Panel panelPreprocess2;
        private System.Windows.Forms.Panel panelPreprocess3;
        private System.Windows.Forms.Panel panelPreprocess4;
        private System.Windows.Forms.Label labelPreprocess1Title;
        private System.Windows.Forms.Label labelPreprocess2Title;
        private System.Windows.Forms.Label labelPreprocess3Title;
        private System.Windows.Forms.Label labelPreprocess4Title;
        private System.Windows.Forms.PictureBox pictureBoxPreprocess1;
        private System.Windows.Forms.PictureBox pictureBoxPreprocess2;
        private System.Windows.Forms.PictureBox pictureBoxPreprocess3;
        private System.Windows.Forms.PictureBox pictureBoxPreprocess4;
        private System.Windows.Forms.TabControl tabControlPreprocess;
        private System.Windows.Forms.TabPage tabPagePreprocess1;
        private System.Windows.Forms.TabPage tabPagePreprocess2;
        private System.Windows.Forms.TabPage tabPagePreprocess3;
        private System.Windows.Forms.TabPage tabPagePreprocess4;
        private System.Windows.Forms.CheckBox checkBoxPreprocess1Enabled;
        private System.Windows.Forms.CheckBox checkBoxPreprocess2Enabled;
        private System.Windows.Forms.CheckBox checkBoxPreprocess3Enabled;
        private System.Windows.Forms.CheckBox checkBoxPreprocess4Enabled;
        private System.Windows.Forms.TrackBar trackBarThreshold1;
        private System.Windows.Forms.TrackBar trackBarThreshold2;
        private System.Windows.Forms.TrackBar trackBarThreshold3;
        private System.Windows.Forms.TrackBar trackBarThreshold4;
        private System.Windows.Forms.NumericUpDown numericThreshold1;
        private System.Windows.Forms.NumericUpDown numericThreshold2;
        private System.Windows.Forms.NumericUpDown numericThreshold3;
        private System.Windows.Forms.NumericUpDown numericThreshold4;
        private System.Windows.Forms.NumericUpDown numericErode1;
        private System.Windows.Forms.NumericUpDown numericErode2;
        private System.Windows.Forms.NumericUpDown numericErode3;
        private System.Windows.Forms.NumericUpDown numericErode4;
        private System.Windows.Forms.NumericUpDown numericDilate1;
        private System.Windows.Forms.NumericUpDown numericDilate2;
        private System.Windows.Forms.NumericUpDown numericDilate3;
        private System.Windows.Forms.NumericUpDown numericDilate4;
        private System.Windows.Forms.NumericUpDown numericOpen1;
        private System.Windows.Forms.NumericUpDown numericOpen2;
        private System.Windows.Forms.NumericUpDown numericOpen3;
        private System.Windows.Forms.NumericUpDown numericOpen4;
        private System.Windows.Forms.NumericUpDown numericClose1;
        private System.Windows.Forms.NumericUpDown numericClose2;
        private System.Windows.Forms.NumericUpDown numericClose3;
        private System.Windows.Forms.NumericUpDown numericClose4;
        private System.Windows.Forms.Label labelThreshold1;
        private System.Windows.Forms.Label labelThreshold2;
        private System.Windows.Forms.Label labelThreshold3;
        private System.Windows.Forms.Label labelThreshold4;
        private System.Windows.Forms.Label labelErode1;
        private System.Windows.Forms.Label labelErode2;
        private System.Windows.Forms.Label labelErode3;
        private System.Windows.Forms.Label labelErode4;
        private System.Windows.Forms.Label labelDilate1;
        private System.Windows.Forms.Label labelDilate2;
        private System.Windows.Forms.Label labelDilate3;
        private System.Windows.Forms.Label labelDilate4;
        private System.Windows.Forms.Label labelOpen1;
        private System.Windows.Forms.Label labelOpen2;
        private System.Windows.Forms.Label labelOpen3;
        private System.Windows.Forms.Label labelOpen4;
        private System.Windows.Forms.Label labelClose1;
        private System.Windows.Forms.Label labelClose2;
        private System.Windows.Forms.Label labelClose3;
        private System.Windows.Forms.Label labelClose4;
        private System.Windows.Forms.OpenFileDialog openFileDialogImage;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.menuStripMain = new System.Windows.Forms.MenuStrip();
            this.menuFile = new System.Windows.Forms.ToolStripMenuItem();
            this.menuOpenImage = new System.Windows.Forms.ToolStripMenuItem();
            this.menuFileSeparator = new System.Windows.Forms.ToolStripSeparator();
            this.menuExit = new System.Windows.Forms.ToolStripMenuItem();
            this.menuEdit = new System.Windows.Forms.ToolStripMenuItem();
            this.menuView = new System.Windows.Forms.ToolStripMenuItem();
            this.menuHelp = new System.Windows.Forms.ToolStripMenuItem();
            this.panelSidebar = new System.Windows.Forms.Panel();
            this.labelAppName = new System.Windows.Forms.Label();
            this.labelNavigation = new System.Windows.Forms.Label();
            this.buttonLoadImage = new System.Windows.Forms.Button();
            this.labelOpenCvStatus = new System.Windows.Forms.Label();
            this.panelMain = new System.Windows.Forms.Panel();
            this.panelHeader = new System.Windows.Forms.Panel();
            this.labelTitle = new System.Windows.Forms.Label();
            this.labelImageInfo = new System.Windows.Forms.Label();
            this.tabControlMain = new System.Windows.Forms.TabControl();
            this.tabPageImageViewer = new System.Windows.Forms.TabPage();
            this.tabPageBinarization = new System.Windows.Forms.TabPage();
            this.labelWorkspace = new System.Windows.Forms.Label();
            this.panelImageViewport = new System.Windows.Forms.Panel();
            this.pictureBoxImage = new System.Windows.Forms.PictureBox();
            this.panelPreprocess1 = new System.Windows.Forms.Panel();
            this.panelPreprocess2 = new System.Windows.Forms.Panel();
            this.panelPreprocess3 = new System.Windows.Forms.Panel();
            this.panelPreprocess4 = new System.Windows.Forms.Panel();
            this.labelPreprocess1Title = new System.Windows.Forms.Label();
            this.labelPreprocess2Title = new System.Windows.Forms.Label();
            this.labelPreprocess3Title = new System.Windows.Forms.Label();
            this.labelPreprocess4Title = new System.Windows.Forms.Label();
            this.pictureBoxPreprocess1 = new System.Windows.Forms.PictureBox();
            this.pictureBoxPreprocess2 = new System.Windows.Forms.PictureBox();
            this.pictureBoxPreprocess3 = new System.Windows.Forms.PictureBox();
            this.pictureBoxPreprocess4 = new System.Windows.Forms.PictureBox();
            this.tabControlPreprocess = new System.Windows.Forms.TabControl();
            this.tabPagePreprocess1 = new System.Windows.Forms.TabPage();
            this.tabPagePreprocess2 = new System.Windows.Forms.TabPage();
            this.tabPagePreprocess3 = new System.Windows.Forms.TabPage();
            this.tabPagePreprocess4 = new System.Windows.Forms.TabPage();
            this.checkBoxPreprocess1Enabled = new System.Windows.Forms.CheckBox();
            this.checkBoxPreprocess2Enabled = new System.Windows.Forms.CheckBox();
            this.checkBoxPreprocess3Enabled = new System.Windows.Forms.CheckBox();
            this.checkBoxPreprocess4Enabled = new System.Windows.Forms.CheckBox();
            this.trackBarThreshold1 = new System.Windows.Forms.TrackBar();
            this.trackBarThreshold2 = new System.Windows.Forms.TrackBar();
            this.trackBarThreshold3 = new System.Windows.Forms.TrackBar();
            this.trackBarThreshold4 = new System.Windows.Forms.TrackBar();
            this.numericThreshold1 = new System.Windows.Forms.NumericUpDown();
            this.numericThreshold2 = new System.Windows.Forms.NumericUpDown();
            this.numericThreshold3 = new System.Windows.Forms.NumericUpDown();
            this.numericThreshold4 = new System.Windows.Forms.NumericUpDown();
            this.numericErode1 = new System.Windows.Forms.NumericUpDown();
            this.numericErode2 = new System.Windows.Forms.NumericUpDown();
            this.numericErode3 = new System.Windows.Forms.NumericUpDown();
            this.numericErode4 = new System.Windows.Forms.NumericUpDown();
            this.numericDilate1 = new System.Windows.Forms.NumericUpDown();
            this.numericDilate2 = new System.Windows.Forms.NumericUpDown();
            this.numericDilate3 = new System.Windows.Forms.NumericUpDown();
            this.numericDilate4 = new System.Windows.Forms.NumericUpDown();
            this.numericOpen1 = new System.Windows.Forms.NumericUpDown();
            this.numericOpen2 = new System.Windows.Forms.NumericUpDown();
            this.numericOpen3 = new System.Windows.Forms.NumericUpDown();
            this.numericOpen4 = new System.Windows.Forms.NumericUpDown();
            this.numericClose1 = new System.Windows.Forms.NumericUpDown();
            this.numericClose2 = new System.Windows.Forms.NumericUpDown();
            this.numericClose3 = new System.Windows.Forms.NumericUpDown();
            this.numericClose4 = new System.Windows.Forms.NumericUpDown();
            this.labelThreshold1 = new System.Windows.Forms.Label();
            this.labelThreshold2 = new System.Windows.Forms.Label();
            this.labelThreshold3 = new System.Windows.Forms.Label();
            this.labelThreshold4 = new System.Windows.Forms.Label();
            this.labelErode1 = new System.Windows.Forms.Label();
            this.labelErode2 = new System.Windows.Forms.Label();
            this.labelErode3 = new System.Windows.Forms.Label();
            this.labelErode4 = new System.Windows.Forms.Label();
            this.labelDilate1 = new System.Windows.Forms.Label();
            this.labelDilate2 = new System.Windows.Forms.Label();
            this.labelDilate3 = new System.Windows.Forms.Label();
            this.labelDilate4 = new System.Windows.Forms.Label();
            this.labelOpen1 = new System.Windows.Forms.Label();
            this.labelOpen2 = new System.Windows.Forms.Label();
            this.labelOpen3 = new System.Windows.Forms.Label();
            this.labelOpen4 = new System.Windows.Forms.Label();
            this.labelClose1 = new System.Windows.Forms.Label();
            this.labelClose2 = new System.Windows.Forms.Label();
            this.labelClose3 = new System.Windows.Forms.Label();
            this.labelClose4 = new System.Windows.Forms.Label();
            this.openFileDialogImage = new System.Windows.Forms.OpenFileDialog();
            this.SuspendLayout();

            this.menuStripMain.BackColor = System.Drawing.Color.FromArgb(248, 247, 247);
            this.menuStripMain.Font = new System.Drawing.Font("Microsoft JhengHei UI", 11F);
            this.menuStripMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] { this.menuFile, this.menuEdit, this.menuView, this.menuHelp });
            this.menuStripMain.Location = new System.Drawing.Point(0, 0);
            this.menuStripMain.Name = "menuStripMain";
            this.menuStripMain.Padding = new System.Windows.Forms.Padding(18, 8, 0, 8);
            this.menuStripMain.Size = new System.Drawing.Size(1280, 42);
            this.menuFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] { this.menuOpenImage, this.menuFileSeparator, this.menuExit });
            this.menuFile.Name = "menuFile";
            this.menuFile.Text = "檔案";
            this.menuOpenImage.Name = "menuOpenImage";
            this.menuOpenImage.Text = "讀取圖片";
            this.menuOpenImage.ShortcutKeys = System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O;
            this.menuOpenImage.Click += new System.EventHandler(this.LoadImageButton_Click);
            this.menuExit.Name = "menuExit";
            this.menuExit.Text = "結束";
            this.menuExit.Click += new System.EventHandler(this.CloseButton_Click);
            this.menuEdit.Name = "menuEdit";
            this.menuEdit.Text = "編輯";
            this.menuView.Name = "menuView";
            this.menuView.Text = "檢視";
            this.menuHelp.Name = "menuHelp";
            this.menuHelp.Text = "說明";

            this.panelSidebar.BackColor = System.Drawing.Color.FromArgb(239, 243, 245);
            this.panelSidebar.Controls.Add(this.labelAppName);
            this.panelSidebar.Controls.Add(this.labelNavigation);
            this.panelSidebar.Controls.Add(this.buttonLoadImage);
            this.panelSidebar.Controls.Add(this.labelOpenCvStatus);
            this.panelSidebar.Location = new System.Drawing.Point(0, 42);
            this.panelSidebar.Name = "panelSidebar";
            this.panelSidebar.Size = new System.Drawing.Size(240, 758);
            this.labelAppName.AutoSize = true;
            this.labelAppName.Font = new System.Drawing.Font("Microsoft JhengHei UI", 16F, System.Drawing.FontStyle.Bold);
            this.labelAppName.Location = new System.Drawing.Point(20, 25);
            this.labelAppName.Name = "labelAppName";
            this.labelAppName.Text = "AOI Viewer";
            this.labelNavigation.AutoSize = true;
            this.labelNavigation.ForeColor = System.Drawing.Color.FromArgb(145, 149, 153);
            this.labelNavigation.Location = new System.Drawing.Point(20, 83);
            this.labelNavigation.Name = "labelNavigation";
            this.labelNavigation.Text = "工作項目";
            this.buttonLoadImage.BackColor = System.Drawing.Color.FromArgb(224, 228, 231);
            this.buttonLoadImage.FlatAppearance.BorderSize = 0;
            this.buttonLoadImage.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonLoadImage.Font = new System.Drawing.Font("Microsoft JhengHei UI", 12F);
            this.buttonLoadImage.Location = new System.Drawing.Point(16, 116);
            this.buttonLoadImage.Name = "buttonLoadImage";
            this.buttonLoadImage.Padding = new System.Windows.Forms.Padding(14, 0, 0, 0);
            this.buttonLoadImage.Size = new System.Drawing.Size(208, 48);
            this.buttonLoadImage.Text = "+   讀取圖片";
            this.buttonLoadImage.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonLoadImage.UseVisualStyleBackColor = false;
            this.buttonLoadImage.Click += new System.EventHandler(this.LoadImageButton_Click);
            this.labelOpenCvStatus.AutoSize = true;
            this.labelOpenCvStatus.ForeColor = System.Drawing.Color.FromArgb(110, 115, 120);
            this.labelOpenCvStatus.Location = new System.Drawing.Point(24, 706);
            this.labelOpenCvStatus.Name = "labelOpenCvStatus";
            this.labelOpenCvStatus.Text = "OpenCV 4.13 已就緒";

            this.panelMain.BackColor = System.Drawing.Color.FromArgb(248, 249, 250);
            this.panelMain.Controls.Add(this.panelHeader);
            this.panelMain.Controls.Add(this.tabControlMain);
            this.panelMain.Location = new System.Drawing.Point(240, 42);
            this.panelMain.Name = "panelMain";
            this.panelMain.Size = new System.Drawing.Size(1040, 758);
            this.panelHeader.BackColor = System.Drawing.Color.White;
            this.panelHeader.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelHeader.Controls.Add(this.labelTitle);
            this.panelHeader.Controls.Add(this.labelImageInfo);
            this.panelHeader.Location = new System.Drawing.Point(0, 0);
            this.panelHeader.Name = "panelHeader";
            this.panelHeader.Size = new System.Drawing.Size(1040, 72);
            this.labelTitle.AutoSize = true;
            this.labelTitle.Font = new System.Drawing.Font("Microsoft JhengHei UI", 14F, System.Drawing.FontStyle.Bold);
            this.labelTitle.Location = new System.Drawing.Point(28, 23);
            this.labelTitle.Name = "labelTitle";
            this.labelTitle.Text = "AOI 影像工具";
            this.labelImageInfo.AutoSize = true;
            this.labelImageInfo.ForeColor = System.Drawing.Color.FromArgb(125, 129, 134);
            this.labelImageInfo.Location = new System.Drawing.Point(190, 28);
            this.labelImageInfo.Name = "labelImageInfo";
            this.labelImageInfo.Text = "尚未讀取圖片";

            this.tabControlMain.Controls.Add(this.tabPageImageViewer);
            this.tabControlMain.Controls.Add(this.tabPageBinarization);
            this.tabControlMain.Font = new System.Drawing.Font("Microsoft JhengHei UI", 10F);
            this.tabControlMain.Location = new System.Drawing.Point(0, 72);
            this.tabControlMain.Name = "tabControlMain";
            this.tabControlMain.SelectedIndex = 0;
            this.tabControlMain.Size = new System.Drawing.Size(1040, 686);
            this.tabPageImageViewer.BackColor = System.Drawing.Color.FromArgb(248, 249, 250);
            this.tabPageImageViewer.Controls.Add(this.labelWorkspace);
            this.tabPageImageViewer.Controls.Add(this.panelImageViewport);
            this.tabPageImageViewer.Location = new System.Drawing.Point(4, 26);
            this.tabPageImageViewer.Name = "tabPageImageViewer";
            this.tabPageImageViewer.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageImageViewer.Size = new System.Drawing.Size(1032, 656);
            this.tabPageImageViewer.Text = "圖片檢視";
            this.labelWorkspace.AutoSize = true;
            this.labelWorkspace.ForeColor = System.Drawing.Color.FromArgb(130, 134, 138);
            this.labelWorkspace.Location = new System.Drawing.Point(28, 18);
            this.labelWorkspace.Name = "labelWorkspace";
            this.labelWorkspace.Text = "原始圖片";
            this.panelImageViewport.BackColor = System.Drawing.Color.FromArgb(239, 241, 243);
            this.panelImageViewport.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelImageViewport.Controls.Add(this.pictureBoxImage);
            this.panelImageViewport.Location = new System.Drawing.Point(28, 46);
            this.panelImageViewport.Name = "panelImageViewport";
            this.panelImageViewport.Size = new System.Drawing.Size(820, 570);
            this.panelImageViewport.MouseEnter += new System.EventHandler(this.ImageViewport_MouseEnter);
            this.panelImageViewport.MouseWheel += new System.Windows.Forms.MouseEventHandler(this.PictureBoxImage_MouseWheel);
            this.pictureBoxImage.BackColor = System.Drawing.Color.FromArgb(239, 241, 243);
            this.pictureBoxImage.Location = new System.Drawing.Point(0, 0);
            this.pictureBoxImage.Name = "pictureBoxImage";
            this.pictureBoxImage.Size = new System.Drawing.Size(818, 568);
            this.pictureBoxImage.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBoxImage.TabStop = true;
            this.pictureBoxImage.MouseDown += new System.Windows.Forms.MouseEventHandler(this.PictureBoxImage_MouseDown);
            this.pictureBoxImage.MouseEnter += new System.EventHandler(this.ImageViewport_MouseEnter);
            this.pictureBoxImage.MouseMove += new System.Windows.Forms.MouseEventHandler(this.PictureBoxImage_MouseMove);
            this.pictureBoxImage.MouseUp += new System.Windows.Forms.MouseEventHandler(this.PictureBoxImage_MouseUp);
            this.pictureBoxImage.MouseWheel += new System.Windows.Forms.MouseEventHandler(this.PictureBoxImage_MouseWheel);

            this.tabPageBinarization.BackColor = System.Drawing.Color.FromArgb(248, 249, 250);
            this.tabPageBinarization.Controls.Add(this.panelPreprocess1);
            this.tabPageBinarization.Controls.Add(this.panelPreprocess2);
            this.tabPageBinarization.Controls.Add(this.panelPreprocess3);
            this.tabPageBinarization.Controls.Add(this.panelPreprocess4);
            this.tabPageBinarization.Controls.Add(this.tabControlPreprocess);
            this.tabPageBinarization.Location = new System.Drawing.Point(4, 26);
            this.tabPageBinarization.Name = "tabPageBinarization";
            this.tabPageBinarization.Padding = new System.Windows.Forms.Padding(3);
            this.tabPageBinarization.Size = new System.Drawing.Size(1032, 656);
            this.tabPageBinarization.Text = "二值化處理";

            this.panelPreprocess1.BackColor = System.Drawing.Color.White;
            this.panelPreprocess1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelPreprocess1.Controls.Add(this.labelPreprocess1Title);
            this.panelPreprocess1.Controls.Add(this.pictureBoxPreprocess1);
            this.panelPreprocess1.Location = new System.Drawing.Point(24, 20);
            this.panelPreprocess1.Name = "panelPreprocess1";
            this.panelPreprocess1.Size = new System.Drawing.Size(218, 186);
            this.labelPreprocess1Title.AutoSize = true;
            this.labelPreprocess1Title.Location = new System.Drawing.Point(8, 6);
            this.labelPreprocess1Title.Name = "labelPreprocess1Title";
            this.labelPreprocess1Title.Text = "1  白物件  Gray > T";
            this.pictureBoxPreprocess1.BackColor = System.Drawing.Color.FromArgb(232, 234, 236);
            this.pictureBoxPreprocess1.Location = new System.Drawing.Point(8, 28);
            this.pictureBoxPreprocess1.Name = "pictureBoxPreprocess1";
            this.pictureBoxPreprocess1.Size = new System.Drawing.Size(200, 148);
            this.pictureBoxPreprocess1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxPreprocess1.TabStop = false;

            this.panelPreprocess2.BackColor = System.Drawing.Color.White;
            this.panelPreprocess2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelPreprocess2.Controls.Add(this.labelPreprocess2Title);
            this.panelPreprocess2.Controls.Add(this.pictureBoxPreprocess2);
            this.panelPreprocess2.Location = new System.Drawing.Point(266, 20);
            this.panelPreprocess2.Name = "panelPreprocess2";
            this.panelPreprocess2.Size = new System.Drawing.Size(218, 186);
            this.labelPreprocess2Title.AutoSize = true;
            this.labelPreprocess2Title.Location = new System.Drawing.Point(8, 6);
            this.labelPreprocess2Title.Name = "labelPreprocess2Title";
            this.labelPreprocess2Title.Text = "2  白物件  Gray > T";
            this.pictureBoxPreprocess2.BackColor = System.Drawing.Color.FromArgb(232, 234, 236);
            this.pictureBoxPreprocess2.Location = new System.Drawing.Point(8, 28);
            this.pictureBoxPreprocess2.Name = "pictureBoxPreprocess2";
            this.pictureBoxPreprocess2.Size = new System.Drawing.Size(200, 148);
            this.pictureBoxPreprocess2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxPreprocess2.TabStop = false;

            this.panelPreprocess3.BackColor = System.Drawing.Color.White;
            this.panelPreprocess3.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelPreprocess3.Controls.Add(this.labelPreprocess3Title);
            this.panelPreprocess3.Controls.Add(this.pictureBoxPreprocess3);
            this.panelPreprocess3.Location = new System.Drawing.Point(508, 20);
            this.panelPreprocess3.Name = "panelPreprocess3";
            this.panelPreprocess3.Size = new System.Drawing.Size(218, 186);
            this.labelPreprocess3Title.AutoSize = true;
            this.labelPreprocess3Title.Location = new System.Drawing.Point(8, 6);
            this.labelPreprocess3Title.Name = "labelPreprocess3Title";
            this.labelPreprocess3Title.Text = "3  黑物件  Gray < T";
            this.pictureBoxPreprocess3.BackColor = System.Drawing.Color.FromArgb(232, 234, 236);
            this.pictureBoxPreprocess3.Location = new System.Drawing.Point(8, 28);
            this.pictureBoxPreprocess3.Name = "pictureBoxPreprocess3";
            this.pictureBoxPreprocess3.Size = new System.Drawing.Size(200, 148);
            this.pictureBoxPreprocess3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxPreprocess3.TabStop = false;

            this.panelPreprocess4.BackColor = System.Drawing.Color.White;
            this.panelPreprocess4.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelPreprocess4.Controls.Add(this.labelPreprocess4Title);
            this.panelPreprocess4.Controls.Add(this.pictureBoxPreprocess4);
            this.panelPreprocess4.Location = new System.Drawing.Point(750, 20);
            this.panelPreprocess4.Name = "panelPreprocess4";
            this.panelPreprocess4.Size = new System.Drawing.Size(218, 186);
            this.labelPreprocess4Title.AutoSize = true;
            this.labelPreprocess4Title.Location = new System.Drawing.Point(8, 6);
            this.labelPreprocess4Title.Name = "labelPreprocess4Title";
            this.labelPreprocess4Title.Text = "4  黑物件  Gray < T";
            this.pictureBoxPreprocess4.BackColor = System.Drawing.Color.FromArgb(232, 234, 236);
            this.pictureBoxPreprocess4.Location = new System.Drawing.Point(8, 28);
            this.pictureBoxPreprocess4.Name = "pictureBoxPreprocess4";
            this.pictureBoxPreprocess4.Size = new System.Drawing.Size(200, 148);
            this.pictureBoxPreprocess4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBoxPreprocess4.TabStop = false;

            this.tabControlPreprocess.Controls.Add(this.tabPagePreprocess1);
            this.tabControlPreprocess.Controls.Add(this.tabPagePreprocess2);
            this.tabControlPreprocess.Controls.Add(this.tabPagePreprocess3);
            this.tabControlPreprocess.Controls.Add(this.tabPagePreprocess4);
            this.tabControlPreprocess.Location = new System.Drawing.Point(24, 224);
            this.tabControlPreprocess.Name = "tabControlPreprocess";
            this.tabControlPreprocess.SelectedIndex = 0;
            this.tabControlPreprocess.Size = new System.Drawing.Size(944, 238);

            this.tabPagePreprocess1.BackColor = System.Drawing.Color.White;
            this.tabPagePreprocess1.Controls.Add(this.checkBoxPreprocess1Enabled);
            this.tabPagePreprocess1.Controls.Add(this.labelThreshold1);
            this.tabPagePreprocess1.Controls.Add(this.trackBarThreshold1);
            this.tabPagePreprocess1.Controls.Add(this.numericThreshold1);
            this.tabPagePreprocess1.Controls.Add(this.labelErode1);
            this.tabPagePreprocess1.Controls.Add(this.numericErode1);
            this.tabPagePreprocess1.Controls.Add(this.labelDilate1);
            this.tabPagePreprocess1.Controls.Add(this.numericDilate1);
            this.tabPagePreprocess1.Controls.Add(this.labelOpen1);
            this.tabPagePreprocess1.Controls.Add(this.numericOpen1);
            this.tabPagePreprocess1.Controls.Add(this.labelClose1);
            this.tabPagePreprocess1.Controls.Add(this.numericClose1);
            this.tabPagePreprocess1.Name = "tabPagePreprocess1";
            this.tabPagePreprocess1.Text = "前處理 1 - 白物件";
            this.checkBoxPreprocess1Enabled.AutoSize = true;
            this.checkBoxPreprocess1Enabled.Checked = true;
            this.checkBoxPreprocess1Enabled.Location = new System.Drawing.Point(16, 15);
            this.checkBoxPreprocess1Enabled.Name = "checkBoxPreprocess1Enabled";
            this.checkBoxPreprocess1Enabled.Text = "啟用此組前處理";
            this.checkBoxPreprocess1Enabled.CheckedChanged += new System.EventHandler(this.PreprocessEnabled_CheckedChanged);
            this.labelThreshold1.AutoSize = true;
            this.labelThreshold1.Location = new System.Drawing.Point(16, 54);
            this.labelThreshold1.Name = "labelThreshold1";
            this.labelThreshold1.Text = "Threshold";
            this.trackBarThreshold1.Location = new System.Drawing.Point(100, 43);
            this.trackBarThreshold1.Maximum = 255;
            this.trackBarThreshold1.Name = "trackBarThreshold1";
            this.trackBarThreshold1.TickFrequency = 32;
            this.trackBarThreshold1.Value = 128;
            this.trackBarThreshold1.Size = new System.Drawing.Size(430, 45);
            this.trackBarThreshold1.Scroll += new System.EventHandler(this.ThresholdTrackBar_Scroll);
            this.numericThreshold1.Location = new System.Drawing.Point(540, 48);
            this.numericThreshold1.Maximum = 255;
            this.numericThreshold1.Name = "numericThreshold1";
            this.numericThreshold1.Value = 128;
            this.numericThreshold1.ValueChanged += new System.EventHandler(this.ThresholdValue_ValueChanged);
            this.labelErode1.AutoSize = true;
            this.labelErode1.Location = new System.Drawing.Point(16, 111);
            this.labelErode1.Text = "Erode";
            this.numericErode1.Location = new System.Drawing.Point(81, 106);
            this.numericErode1.Maximum = 20;
            this.numericErode1.Name = "numericErode1";
            this.numericErode1.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelDilate1.AutoSize = true;
            this.labelDilate1.Location = new System.Drawing.Point(180, 111);
            this.labelDilate1.Text = "Dilate";
            this.numericDilate1.Location = new System.Drawing.Point(245, 106);
            this.numericDilate1.Maximum = 20;
            this.numericDilate1.Name = "numericDilate1";
            this.numericDilate1.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelOpen1.AutoSize = true;
            this.labelOpen1.Location = new System.Drawing.Point(344, 111);
            this.labelOpen1.Text = "Open";
            this.numericOpen1.Location = new System.Drawing.Point(409, 106);
            this.numericOpen1.Maximum = 20;
            this.numericOpen1.Name = "numericOpen1";
            this.numericOpen1.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelClose1.AutoSize = true;
            this.labelClose1.Location = new System.Drawing.Point(508, 111);
            this.labelClose1.Text = "Close";
            this.numericClose1.Location = new System.Drawing.Point(573, 106);
            this.numericClose1.Maximum = 20;
            this.numericClose1.Name = "numericClose1";
            this.numericClose1.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);

            this.tabPagePreprocess2.BackColor = System.Drawing.Color.White;
            this.tabPagePreprocess2.Controls.Add(this.checkBoxPreprocess2Enabled);
            this.tabPagePreprocess2.Controls.Add(this.labelThreshold2);
            this.tabPagePreprocess2.Controls.Add(this.trackBarThreshold2);
            this.tabPagePreprocess2.Controls.Add(this.numericThreshold2);
            this.tabPagePreprocess2.Controls.Add(this.labelErode2);
            this.tabPagePreprocess2.Controls.Add(this.numericErode2);
            this.tabPagePreprocess2.Controls.Add(this.labelDilate2);
            this.tabPagePreprocess2.Controls.Add(this.numericDilate2);
            this.tabPagePreprocess2.Controls.Add(this.labelOpen2);
            this.tabPagePreprocess2.Controls.Add(this.numericOpen2);
            this.tabPagePreprocess2.Controls.Add(this.labelClose2);
            this.tabPagePreprocess2.Controls.Add(this.numericClose2);
            this.tabPagePreprocess2.Name = "tabPagePreprocess2";
            this.tabPagePreprocess2.Text = "前處理 2 - 白物件";
            this.checkBoxPreprocess2Enabled.AutoSize = true;
            this.checkBoxPreprocess2Enabled.Checked = true;
            this.checkBoxPreprocess2Enabled.Location = new System.Drawing.Point(16, 15);
            this.checkBoxPreprocess2Enabled.Name = "checkBoxPreprocess2Enabled";
            this.checkBoxPreprocess2Enabled.Text = "啟用此組前處理";
            this.checkBoxPreprocess2Enabled.CheckedChanged += new System.EventHandler(this.PreprocessEnabled_CheckedChanged);
            this.labelThreshold2.AutoSize = true;
            this.labelThreshold2.Location = new System.Drawing.Point(16, 54);
            this.labelThreshold2.Text = "Threshold";
            this.trackBarThreshold2.Location = new System.Drawing.Point(100, 43);
            this.trackBarThreshold2.Maximum = 255;
            this.trackBarThreshold2.Name = "trackBarThreshold2";
            this.trackBarThreshold2.TickFrequency = 32;
            this.trackBarThreshold2.Value = 128;
            this.trackBarThreshold2.Size = new System.Drawing.Size(430, 45);
            this.trackBarThreshold2.Scroll += new System.EventHandler(this.ThresholdTrackBar_Scroll);
            this.numericThreshold2.Location = new System.Drawing.Point(540, 48);
            this.numericThreshold2.Maximum = 255;
            this.numericThreshold2.Name = "numericThreshold2";
            this.numericThreshold2.Value = 128;
            this.numericThreshold2.ValueChanged += new System.EventHandler(this.ThresholdValue_ValueChanged);
            this.labelErode2.AutoSize = true;
            this.labelErode2.Location = new System.Drawing.Point(16, 111);
            this.labelErode2.Text = "Erode";
            this.numericErode2.Location = new System.Drawing.Point(81, 106);
            this.numericErode2.Maximum = 20;
            this.numericErode2.Name = "numericErode2";
            this.numericErode2.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelDilate2.AutoSize = true;
            this.labelDilate2.Location = new System.Drawing.Point(180, 111);
            this.labelDilate2.Text = "Dilate";
            this.numericDilate2.Location = new System.Drawing.Point(245, 106);
            this.numericDilate2.Maximum = 20;
            this.numericDilate2.Name = "numericDilate2";
            this.numericDilate2.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelOpen2.AutoSize = true;
            this.labelOpen2.Location = new System.Drawing.Point(344, 111);
            this.labelOpen2.Text = "Open";
            this.numericOpen2.Location = new System.Drawing.Point(409, 106);
            this.numericOpen2.Maximum = 20;
            this.numericOpen2.Name = "numericOpen2";
            this.numericOpen2.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelClose2.AutoSize = true;
            this.labelClose2.Location = new System.Drawing.Point(508, 111);
            this.labelClose2.Text = "Close";
            this.numericClose2.Location = new System.Drawing.Point(573, 106);
            this.numericClose2.Maximum = 20;
            this.numericClose2.Name = "numericClose2";
            this.numericClose2.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);

            this.tabPagePreprocess3.BackColor = System.Drawing.Color.White;
            this.tabPagePreprocess3.Controls.Add(this.checkBoxPreprocess3Enabled);
            this.tabPagePreprocess3.Controls.Add(this.labelThreshold3);
            this.tabPagePreprocess3.Controls.Add(this.trackBarThreshold3);
            this.tabPagePreprocess3.Controls.Add(this.numericThreshold3);
            this.tabPagePreprocess3.Controls.Add(this.labelErode3);
            this.tabPagePreprocess3.Controls.Add(this.numericErode3);
            this.tabPagePreprocess3.Controls.Add(this.labelDilate3);
            this.tabPagePreprocess3.Controls.Add(this.numericDilate3);
            this.tabPagePreprocess3.Controls.Add(this.labelOpen3);
            this.tabPagePreprocess3.Controls.Add(this.numericOpen3);
            this.tabPagePreprocess3.Controls.Add(this.labelClose3);
            this.tabPagePreprocess3.Controls.Add(this.numericClose3);
            this.tabPagePreprocess3.Name = "tabPagePreprocess3";
            this.tabPagePreprocess3.Text = "前處理 3 - 黑物件";
            this.checkBoxPreprocess3Enabled.AutoSize = true;
            this.checkBoxPreprocess3Enabled.Checked = true;
            this.checkBoxPreprocess3Enabled.Location = new System.Drawing.Point(16, 15);
            this.checkBoxPreprocess3Enabled.Name = "checkBoxPreprocess3Enabled";
            this.checkBoxPreprocess3Enabled.Text = "啟用此組前處理";
            this.checkBoxPreprocess3Enabled.CheckedChanged += new System.EventHandler(this.PreprocessEnabled_CheckedChanged);
            this.labelThreshold3.AutoSize = true;
            this.labelThreshold3.Location = new System.Drawing.Point(16, 54);
            this.labelThreshold3.Text = "Threshold";
            this.trackBarThreshold3.Location = new System.Drawing.Point(100, 43);
            this.trackBarThreshold3.Maximum = 255;
            this.trackBarThreshold3.Name = "trackBarThreshold3";
            this.trackBarThreshold3.TickFrequency = 32;
            this.trackBarThreshold3.Value = 128;
            this.trackBarThreshold3.Size = new System.Drawing.Size(430, 45);
            this.trackBarThreshold3.Scroll += new System.EventHandler(this.ThresholdTrackBar_Scroll);
            this.numericThreshold3.Location = new System.Drawing.Point(540, 48);
            this.numericThreshold3.Maximum = 255;
            this.numericThreshold3.Name = "numericThreshold3";
            this.numericThreshold3.Value = 128;
            this.numericThreshold3.ValueChanged += new System.EventHandler(this.ThresholdValue_ValueChanged);
            this.labelErode3.AutoSize = true;
            this.labelErode3.Location = new System.Drawing.Point(16, 111);
            this.labelErode3.Text = "Erode";
            this.numericErode3.Location = new System.Drawing.Point(81, 106);
            this.numericErode3.Maximum = 20;
            this.numericErode3.Name = "numericErode3";
            this.numericErode3.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelDilate3.AutoSize = true;
            this.labelDilate3.Location = new System.Drawing.Point(180, 111);
            this.labelDilate3.Text = "Dilate";
            this.numericDilate3.Location = new System.Drawing.Point(245, 106);
            this.numericDilate3.Maximum = 20;
            this.numericDilate3.Name = "numericDilate3";
            this.numericDilate3.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelOpen3.AutoSize = true;
            this.labelOpen3.Location = new System.Drawing.Point(344, 111);
            this.labelOpen3.Text = "Open";
            this.numericOpen3.Location = new System.Drawing.Point(409, 106);
            this.numericOpen3.Maximum = 20;
            this.numericOpen3.Name = "numericOpen3";
            this.numericOpen3.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelClose3.AutoSize = true;
            this.labelClose3.Location = new System.Drawing.Point(508, 111);
            this.labelClose3.Text = "Close";
            this.numericClose3.Location = new System.Drawing.Point(573, 106);
            this.numericClose3.Maximum = 20;
            this.numericClose3.Name = "numericClose3";
            this.numericClose3.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);

            this.tabPagePreprocess4.BackColor = System.Drawing.Color.White;
            this.tabPagePreprocess4.Controls.Add(this.checkBoxPreprocess4Enabled);
            this.tabPagePreprocess4.Controls.Add(this.labelThreshold4);
            this.tabPagePreprocess4.Controls.Add(this.trackBarThreshold4);
            this.tabPagePreprocess4.Controls.Add(this.numericThreshold4);
            this.tabPagePreprocess4.Controls.Add(this.labelErode4);
            this.tabPagePreprocess4.Controls.Add(this.numericErode4);
            this.tabPagePreprocess4.Controls.Add(this.labelDilate4);
            this.tabPagePreprocess4.Controls.Add(this.numericDilate4);
            this.tabPagePreprocess4.Controls.Add(this.labelOpen4);
            this.tabPagePreprocess4.Controls.Add(this.numericOpen4);
            this.tabPagePreprocess4.Controls.Add(this.labelClose4);
            this.tabPagePreprocess4.Controls.Add(this.numericClose4);
            this.tabPagePreprocess4.Name = "tabPagePreprocess4";
            this.tabPagePreprocess4.Text = "前處理 4 - 黑物件";
            this.checkBoxPreprocess4Enabled.AutoSize = true;
            this.checkBoxPreprocess4Enabled.Checked = true;
            this.checkBoxPreprocess4Enabled.Location = new System.Drawing.Point(16, 15);
            this.checkBoxPreprocess4Enabled.Name = "checkBoxPreprocess4Enabled";
            this.checkBoxPreprocess4Enabled.Text = "啟用此組前處理";
            this.checkBoxPreprocess4Enabled.CheckedChanged += new System.EventHandler(this.PreprocessEnabled_CheckedChanged);
            this.labelThreshold4.AutoSize = true;
            this.labelThreshold4.Location = new System.Drawing.Point(16, 54);
            this.labelThreshold4.Text = "Threshold";
            this.trackBarThreshold4.Location = new System.Drawing.Point(100, 43);
            this.trackBarThreshold4.Maximum = 255;
            this.trackBarThreshold4.Name = "trackBarThreshold4";
            this.trackBarThreshold4.TickFrequency = 32;
            this.trackBarThreshold4.Value = 128;
            this.trackBarThreshold4.Size = new System.Drawing.Size(430, 45);
            this.trackBarThreshold4.Scroll += new System.EventHandler(this.ThresholdTrackBar_Scroll);
            this.numericThreshold4.Location = new System.Drawing.Point(540, 48);
            this.numericThreshold4.Maximum = 255;
            this.numericThreshold4.Name = "numericThreshold4";
            this.numericThreshold4.Value = 128;
            this.numericThreshold4.ValueChanged += new System.EventHandler(this.ThresholdValue_ValueChanged);
            this.labelErode4.AutoSize = true;
            this.labelErode4.Location = new System.Drawing.Point(16, 111);
            this.labelErode4.Text = "Erode";
            this.numericErode4.Location = new System.Drawing.Point(81, 106);
            this.numericErode4.Maximum = 20;
            this.numericErode4.Name = "numericErode4";
            this.numericErode4.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelDilate4.AutoSize = true;
            this.labelDilate4.Location = new System.Drawing.Point(180, 111);
            this.labelDilate4.Text = "Dilate";
            this.numericDilate4.Location = new System.Drawing.Point(245, 106);
            this.numericDilate4.Maximum = 20;
            this.numericDilate4.Name = "numericDilate4";
            this.numericDilate4.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelOpen4.AutoSize = true;
            this.labelOpen4.Location = new System.Drawing.Point(344, 111);
            this.labelOpen4.Text = "Open";
            this.numericOpen4.Location = new System.Drawing.Point(409, 106);
            this.numericOpen4.Maximum = 20;
            this.numericOpen4.Name = "numericOpen4";
            this.numericOpen4.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);
            this.labelClose4.AutoSize = true;
            this.labelClose4.Location = new System.Drawing.Point(508, 111);
            this.labelClose4.Text = "Close";
            this.numericClose4.Location = new System.Drawing.Point(573, 106);
            this.numericClose4.Maximum = 20;
            this.numericClose4.Name = "numericClose4";
            this.numericClose4.ValueChanged += new System.EventHandler(this.MorphologyValue_ValueChanged);

            this.openFileDialogImage.Filter = "Image Files|*.bmp;*.jpg;*.jpeg;*.png;*.tif;*.tiff|All Files|*.*";
            this.openFileDialogImage.Title = "選擇圖片";
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.FromArgb(248, 249, 250);
            this.ClientSize = new System.Drawing.Size(1280, 800);
            this.Controls.Add(this.panelMain);
            this.Controls.Add(this.panelSidebar);
            this.Controls.Add(this.menuStripMain);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MainMenuStrip = this.menuStripMain;
            this.MaximizeBox = false;
            this.MinimizeBox = true;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "AOI Image Viewer";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.MainForm_FormClosed);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

    }
}
